import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { Formik } from 'formik'
import axios from 'axios'
import styles from '../styles/SignIn.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCheck } from '@fortawesome/free-solid-svg-icons'
import { faUserPlus } from '@fortawesome/free-solid-svg-icons'
import { faSignInAlt } from '@fortawesome/free-solid-svg-icons'



const Login = ({ navigation }) => {
  const router = useRouter();
  const [email, setEmail] = useState();
  const [password, setPassword] = useState();
  const [message, setMessage] = useState();
  const [messageType, setMessageType] = useState();
  const url = 'http://192.168.1.13:3000/api/login';


  const handleLogin = async (credentials, setSubmitting) => {
    handleMessage(null);

    axios
      .post(url, credentials)
      .then(async (response) => {

        const result = response.data;
        const { status, message, data } = result;
        if (status !== 'SUCCESS') {
          handleMessage(message, status);
        } else {
          try {
            router.push('/home');
          }
          catch (error) {
            console.log('error to save data')
          }

        }
        setSubmitting(false);
      })
      .catch((error) => {

        setSubmitting(false);
        handleMessage('An error occurred. Check your network and try again');
        console.log(error);
      });
  };

  const handleMessage = (message, type = '') => {
    setMessage(message);
    setMessageType(type);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.PNG" />
      </Head>
      <div className={styles.nav1}>
        <div className={styles.main1}>
          <a className={styles.txt2} href="./">Sign in</a>
          <a className={styles.txt1} href="./register">Register</a>
        </div>
      </div>


      <div className={styles.topnav}>
        <a href=""> <Image width={50} height={50} src="/logo.PNG" alt="logo" ></Image></a>
        <div className={styles.div2}>
          <a href="home">Home</a>
          <a href="#">About us</a>
          <a href="#">Contact us</a>
          <span className={styles.cercleProfil}><p className={styles.txt3}>Ar</p></span>
        </div>
      </div>
      <form name="formone" >
        <div className={styles.body}>
          <table className={styles.tab1}>
            <div className={styles.verif}>
              <FontAwesomeIcon className={styles.facheck} icon={faCheck} />
            </div>
            <tr >

              <td className={styles.td2}>
                <a href="./register">  <FontAwesomeIcon className={styles.iconuser} icon={faUserPlus} />
                  <p className={styles.txt4}>Register</p></a>
                <p className={styles.txt5}>Browse and find what you need</p>
              </td>
              <td className={styles.td} >
                <a href="./"><FontAwesomeIcon className={styles.iconuser} icon={faSignInAlt} />
                  <p className={styles.txt4}>Sign in</p></a>
                <p className={styles.txt5}>Already have an account then welcome back</p>
              </td>
            </tr>
          </table>
          <Formik
            initialValues={{ email: '', password: '' }}
            onSubmit={(values, { setSubmitting }) => {
              if (email == '' || password == '') {
                handleMessage('Please fill in all fields');
                setSubmitting(false);
              } else {
                handleLogin(values, setSubmitting);
              }
            }}
          >
            {({ handleChange, handleSubmit, values }) => (
              <div className={styles.inputfield}>
                <input className={styles.input} type="email" placeholder='Email*' value={values.email} onChange={handleChange('email')} required />
                <input className={styles.input} type="password" placeholder='Password*' value={values.password} onChange={handleChange('password')} required />
                <button type="submit" className={styles.btnlogin} onClick={handleSubmit}><p className={styles.txt6}>Submit</p></button>
              </div>
            )}
          </Formik>
        </div>
      </form>

      <footer className={styles.footer}>
        <div className={styles.div3} >
          <Image width={150} height={150} src="/logofooter.PNG" alt="logo" ></Image>
          <p className={styles.p1}>© All Rights Reserved.</p>
        </div>
      </footer>

    </div>
  )
}
export default Login;